import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/Providers/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className=''>
      <body
        className={
          inter.className +
          "  overflow-x-hidden transition-colors duration-500 ease-in-out "
        }
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
